// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/weaveworks/pctl/pkg/upgrade/repo"
)

type FakeRepoManager struct {
	CreateBranchWithContentFromMainStub        func(string, func() error) error
	createBranchWithContentFromMainMutex       sync.RWMutex
	createBranchWithContentFromMainArgsForCall []struct {
		arg1 string
		arg2 func() error
	}
	createBranchWithContentFromMainReturns struct {
		result1 error
	}
	createBranchWithContentFromMainReturnsOnCall map[int]struct {
		result1 error
	}
	CreateRepoWithContentStub        func(func() error) error
	createRepoWithContentMutex       sync.RWMutex
	createRepoWithContentArgsForCall []struct {
		arg1 func() error
	}
	createRepoWithContentReturns struct {
		result1 error
	}
	createRepoWithContentReturnsOnCall map[int]struct {
		result1 error
	}
	MergeBranchesStub        func(string, string) (bool, error)
	mergeBranchesMutex       sync.RWMutex
	mergeBranchesArgsForCall []struct {
		arg1 string
		arg2 string
	}
	mergeBranchesReturns struct {
		result1 bool
		result2 error
	}
	mergeBranchesReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMain(arg1 string, arg2 func() error) error {
	fake.createBranchWithContentFromMainMutex.Lock()
	ret, specificReturn := fake.createBranchWithContentFromMainReturnsOnCall[len(fake.createBranchWithContentFromMainArgsForCall)]
	fake.createBranchWithContentFromMainArgsForCall = append(fake.createBranchWithContentFromMainArgsForCall, struct {
		arg1 string
		arg2 func() error
	}{arg1, arg2})
	stub := fake.CreateBranchWithContentFromMainStub
	fakeReturns := fake.createBranchWithContentFromMainReturns
	fake.recordInvocation("CreateBranchWithContentFromMain", []interface{}{arg1, arg2})
	fake.createBranchWithContentFromMainMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMainCallCount() int {
	fake.createBranchWithContentFromMainMutex.RLock()
	defer fake.createBranchWithContentFromMainMutex.RUnlock()
	return len(fake.createBranchWithContentFromMainArgsForCall)
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMainCalls(stub func(string, func() error) error) {
	fake.createBranchWithContentFromMainMutex.Lock()
	defer fake.createBranchWithContentFromMainMutex.Unlock()
	fake.CreateBranchWithContentFromMainStub = stub
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMainArgsForCall(i int) (string, func() error) {
	fake.createBranchWithContentFromMainMutex.RLock()
	defer fake.createBranchWithContentFromMainMutex.RUnlock()
	argsForCall := fake.createBranchWithContentFromMainArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMainReturns(result1 error) {
	fake.createBranchWithContentFromMainMutex.Lock()
	defer fake.createBranchWithContentFromMainMutex.Unlock()
	fake.CreateBranchWithContentFromMainStub = nil
	fake.createBranchWithContentFromMainReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoManager) CreateBranchWithContentFromMainReturnsOnCall(i int, result1 error) {
	fake.createBranchWithContentFromMainMutex.Lock()
	defer fake.createBranchWithContentFromMainMutex.Unlock()
	fake.CreateBranchWithContentFromMainStub = nil
	if fake.createBranchWithContentFromMainReturnsOnCall == nil {
		fake.createBranchWithContentFromMainReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createBranchWithContentFromMainReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoManager) CreateRepoWithContent(arg1 func() error) error {
	fake.createRepoWithContentMutex.Lock()
	ret, specificReturn := fake.createRepoWithContentReturnsOnCall[len(fake.createRepoWithContentArgsForCall)]
	fake.createRepoWithContentArgsForCall = append(fake.createRepoWithContentArgsForCall, struct {
		arg1 func() error
	}{arg1})
	stub := fake.CreateRepoWithContentStub
	fakeReturns := fake.createRepoWithContentReturns
	fake.recordInvocation("CreateRepoWithContent", []interface{}{arg1})
	fake.createRepoWithContentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoManager) CreateRepoWithContentCallCount() int {
	fake.createRepoWithContentMutex.RLock()
	defer fake.createRepoWithContentMutex.RUnlock()
	return len(fake.createRepoWithContentArgsForCall)
}

func (fake *FakeRepoManager) CreateRepoWithContentCalls(stub func(func() error) error) {
	fake.createRepoWithContentMutex.Lock()
	defer fake.createRepoWithContentMutex.Unlock()
	fake.CreateRepoWithContentStub = stub
}

func (fake *FakeRepoManager) CreateRepoWithContentArgsForCall(i int) func() error {
	fake.createRepoWithContentMutex.RLock()
	defer fake.createRepoWithContentMutex.RUnlock()
	argsForCall := fake.createRepoWithContentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRepoManager) CreateRepoWithContentReturns(result1 error) {
	fake.createRepoWithContentMutex.Lock()
	defer fake.createRepoWithContentMutex.Unlock()
	fake.CreateRepoWithContentStub = nil
	fake.createRepoWithContentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoManager) CreateRepoWithContentReturnsOnCall(i int, result1 error) {
	fake.createRepoWithContentMutex.Lock()
	defer fake.createRepoWithContentMutex.Unlock()
	fake.CreateRepoWithContentStub = nil
	if fake.createRepoWithContentReturnsOnCall == nil {
		fake.createRepoWithContentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createRepoWithContentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoManager) MergeBranches(arg1 string, arg2 string) (bool, error) {
	fake.mergeBranchesMutex.Lock()
	ret, specificReturn := fake.mergeBranchesReturnsOnCall[len(fake.mergeBranchesArgsForCall)]
	fake.mergeBranchesArgsForCall = append(fake.mergeBranchesArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.MergeBranchesStub
	fakeReturns := fake.mergeBranchesReturns
	fake.recordInvocation("MergeBranches", []interface{}{arg1, arg2})
	fake.mergeBranchesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoManager) MergeBranchesCallCount() int {
	fake.mergeBranchesMutex.RLock()
	defer fake.mergeBranchesMutex.RUnlock()
	return len(fake.mergeBranchesArgsForCall)
}

func (fake *FakeRepoManager) MergeBranchesCalls(stub func(string, string) (bool, error)) {
	fake.mergeBranchesMutex.Lock()
	defer fake.mergeBranchesMutex.Unlock()
	fake.MergeBranchesStub = stub
}

func (fake *FakeRepoManager) MergeBranchesArgsForCall(i int) (string, string) {
	fake.mergeBranchesMutex.RLock()
	defer fake.mergeBranchesMutex.RUnlock()
	argsForCall := fake.mergeBranchesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepoManager) MergeBranchesReturns(result1 bool, result2 error) {
	fake.mergeBranchesMutex.Lock()
	defer fake.mergeBranchesMutex.Unlock()
	fake.MergeBranchesStub = nil
	fake.mergeBranchesReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoManager) MergeBranchesReturnsOnCall(i int, result1 bool, result2 error) {
	fake.mergeBranchesMutex.Lock()
	defer fake.mergeBranchesMutex.Unlock()
	fake.MergeBranchesStub = nil
	if fake.mergeBranchesReturnsOnCall == nil {
		fake.mergeBranchesReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.mergeBranchesReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createBranchWithContentFromMainMutex.RLock()
	defer fake.createBranchWithContentFromMainMutex.RUnlock()
	fake.createRepoWithContentMutex.RLock()
	defer fake.createRepoWithContentMutex.RUnlock()
	fake.mergeBranchesMutex.RLock()
	defer fake.mergeBranchesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepoManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repo.RepoManager = new(FakeRepoManager)
