// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/weaveworks/pctl/pkg/profile/artifact"
	"github.com/weaveworks/pctl/pkg/profile/builders"

	"github.com/weaveworks/profiles/api/v1alpha1"
)

type FakeBuilder struct {
	BuildStub        func(v1alpha1.Artifact, v1alpha1.ProfileInstallation, v1alpha1.ProfileDefinition) ([]artifact.Artifact, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 v1alpha1.Artifact
		arg2 v1alpha1.ProfileInstallation
		arg3 v1alpha1.ProfileDefinition
	}
	buildReturns struct {
		result1 []artifact.Artifact
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 []artifact.Artifact
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBuilder) Build(arg1 v1alpha1.Artifact, arg2 v1alpha1.ProfileInstallation, arg3 v1alpha1.ProfileDefinition) ([]artifact.Artifact, error) {
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 v1alpha1.Artifact
		arg2 v1alpha1.ProfileInstallation
		arg3 v1alpha1.ProfileDefinition
	}{arg1, arg2, arg3})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2, arg3})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeBuilder) BuildCalls(stub func(v1alpha1.Artifact, v1alpha1.ProfileInstallation, v1alpha1.ProfileDefinition) ([]artifact.Artifact, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *FakeBuilder) BuildArgsForCall(i int) (v1alpha1.Artifact, v1alpha1.ProfileInstallation, v1alpha1.ProfileDefinition) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBuilder) BuildReturns(result1 []artifact.Artifact, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 []artifact.Artifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBuilder) BuildReturnsOnCall(i int, result1 []artifact.Artifact, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 []artifact.Artifact
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 []artifact.Artifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ builders.Builder = new(FakeBuilder)
